name: CommandPointsMobDisguiseBridge
main: pgDev.bukkit.CPMD.CommandPointsMobDisguiseBridge
version: 2.3
author: PG Dev Team
authors: [Devil Boy, DrKabob]
description: Allows normal users to disguise themselves as mobs for CommandPoints!
depend: [CommandPoints]
softdepend: [MobDisguise, DisguiseCraft]

permissions:
    CPMD.disguise.free:
        default: op
        description: Is allowed to disguise for free.